#Configuração de log
logging:
  level:
    com:
      cooperativismo:
        controlevotacao: info
          
#Configuração de contexto
server:
  port: 8080
  servlet:
    context-path: /apicontrole

#Configuração de banco
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: satellite
    url: jdbc:postgresql://localhost:5432/controle_votacao
    username: postgres
  jpa:
    show-sql: false

#Configurações de integração
dominio:
  url: https://user-info.herokuapp.com
endpoint:
  authorized-vote: ${dominio.url}/users/{cpf}